### ISSUE TITLE
malloc error when opening app through push message on iOS

### ISSUE THREAD

**Issue by hgbimonti** [Pushwoosh/push-notifications-sdk#40]
As I have posted on PushWoosh community:

https://community.pushwoosh.com/questions/2012/malloc-error-when-opening-app-through-push-message

I'm using Unity 4.6.3f1, XCode 6.2, iOS 8.3 and testing PushWoosh Unity iOS in my project.

I receive the push, but when I touch the message and open the game it crashes with the following error:

malloc: error for object 0x159c7a00: pointer being freed was not allocated set a breakpoint in malloc_error_break to debug
On line:
UIApplicationMain(argc, argv, nil, [NSString stringWithUTF8String:AppControllerClassName]); in Classes/main.mm

The error happens in my project and in the Sample project that comes with PushWoosh SDK from this GitHub repo.

Thanks!

**Comment by shaders** [comment]
Does it happen with Unity 5.0? Do you have any sample (small and simple) XCode project (exported from Unity) you could send that reproduces the issue?

**Comment by hgbimonti** [comment]
We are unable to install Unity 5 because the project is in the end and it's not a good time for an update.

Our Unity version is 4.6.3f1.

Here is the PushWooshSample project on XCode.
https://www.dropbox.com/s/i6j34rwzypdtf5e/PushWooshSample.zip?dl=0

There's a Xcode printscreen in the zip if that helps.

Thanks!

**Comment by shaders** [comment]
Thanks! I have pushed the fix to the repo.
