### ISSUE TITLE
ios 10 push-notification event not fire and yes it working fine in android

### ISSUE THREAD

**Issue by mobileias** [Pushwoosh/push-notifications-sdk#42]
Hello

I have one issues comes since last one day same code working fine in both ios and android now when i build again after that push-notification event not fire when push come or when click on push from notification in ios 10.0.2 device cordova is 3.9.1. I am using latest pushwoosh plugin 

 All is fine in android .
`<gap:plugin name="pushwoosh-pgb-plugin" source="npm" version="6.2.1"/>
<preference name="phonegap-version" value="cli-5.2.0"/>`
Thanks in advance

**Comment by shaders** [comment]
Hi,

This has been fixed in the latest iOS SDK. 4.1.5
