### ISSUE TITLE
Please help !!

### ISSUE THREAD

**Issue by rajumark** [Pushwoosh/push-notifications-sdk#44]
Hello!
My application have a specific activity for the push. When I receive a
push notification, it must show a screen with informations for the
user.

My current scenario is: When I receive a notification, if my
application is on its main activity, then it automatically open the
correct activity which stands for the data contained in push.
But, if I'm in any other screen besides the main activity, or if my
application is closed/paused, then the notification for the push is
shown at the notification bar. When I select the notification, then my
main activity open.

There is any way to set the activity for the notification click?

 private void createNotification(String title, String messageBody) {

        Intent myIntent = new Intent(this, NotificationActivity.class);

        myIntent.putExtra("NotClick", true);
       // final PendingIntent contentIntent = PendingIntent.getActivity(this, 0, myIntent, 0);
       /* TaskStackBuilder taskStackBuilder = TaskStackBuilder.create(this);
     //   taskStackBuilder.addNextIntentWithParentStack(myIntent);
      taskStackBuilder.addParentStack(HomeActivity.class);
        PendingIntent pendingIntent = taskStackBuilder.getPendingIntent(0, PendingIntent.FLAG_ONE_SHOT);*/

        PendingIntent pendingIntent = PendingIntent.getActivity(this, 0, myIntent, 0);

        Uri notificationSoundURI = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION);
        NotificationCompat.Builder mNotificationBuilder = new NotificationCompat.Builder(this)
                .setSmallIcon(R.drawable.mongo_icon)
                .setContentTitle(title)
                .setContentText(messageBody)
                .setAutoCancel(true)
                .setVibrate(new long[]{100, 250, 100, 250, 100, 250})
                .setSound(notificationSoundURI)
                .setContentIntent(pendingIntent)
                .setPriority(Notification.PRIORITY_MAX);

        NotificationManager notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
        notificationManager.notify(0, mNotificationBuilder.build());
    }

**Comment by wfhm** [comment]
Hi @rajumark ,

> My current scenario is: When I receive a notification, if my
application is on its main activity, then it automatically open the
correct activity which stands for the data contained in push.
But, if I'm in any other screen besides the main activity, or if my
application is closed/paused, then the notification for the push is
shown at the notification bar. When I select the notification, then my
main activity open.

This is quite a strange behavior. Is this issue still persistent? By any chance could you please provide us with a reproducer apk? If it is possible, you can send it to help@pushwoosh.com with a link to this thread.

Also, could you please share your AndroidManifest.xml?

To customize notification open behavior, you should create a custom NotificationServiceExtension. For a full guide please refer to the link below:

https://www.pushwoosh.com/v1.0/docs/customising-android-sdk-50#section-customising-notification-open-behaviour
